# Generated by Django 3.1 on 2020-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('artist', models.CharField(max_length=30)),
                ('singapore_stock', models.IntegerField()),
                ('uk_stock', models.IntegerField()),
                ('cause', models.CharField(choices=[('BRC', 'Beirut Red Cross')], max_length=5)),
            ],
        ),
    ]
