# Generated by Django 3.1 on 2020-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='price',
            field=models.FloatField(verbose_name='Price (£)'),
        ),
    ]
