# Generated by Django 3.1.1 on 2020-09-05 18:39

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200905_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_directory_path),
        ),
    ]
