# Generated by Django 3.1.1 on 2020-09-09 10:23

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sticker_image_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='sticker',
            name='dimensions',
            field=models.CharField(max_length=10, null=True, verbose_name='Dimensions (A x B cm)'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_directory_path, verbose_name='Secondary Image'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Order of appearance(lowest first)'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_directory_path, verbose_name='Primary Image'),
        ),
    ]
