# Generated by Django 3.1.1 on 2020-10-16 14:57

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sticker_price_sg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.models.image_directory_path2)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sticker')),
            ],
        ),
    ]
