# Generated by Django 3.1.1 on 2020-10-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_stickerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='image_2',
        ),
    ]
