# Generated by Django 3.1.1 on 2020-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201018_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='dimensions',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dimensions (A x B cm)'),
        ),
    ]
