# Generated by Django 3.1.1 on 2020-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
