# Generated by Django 3.1.1 on 2020-09-12 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalpages', '0002_auto_20200912_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 23, 1, 952383)),
        ),
    ]
