# Generated by Django 3.1.1 on 2020-09-12 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generalpages', '0003_auto_20200912_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
