# Generated by Django 3.1.1 on 2020-10-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalpages', '0004_auto_20200912_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['status', '-datetime']},
        ),
    ]
